Add a testcase for multiple simultaneous account create
flow-hydraulics/flow-wallet-api pull request #236
Opened 2021-12-15 14:01 UTC by latenssi

2021-12-17 09:26 UTC, nanuuki requested changes
Overall looks good, see comments :) After those it's good to go

2021-12-17 09:26 UTC, nanuuki commented on tests/accounts_service_test.go
> +	if acccounts, err := svcs[0].List(0, 0); err != nil {
typo; `acccounts` => `accounts`

2021-12-17 09:26 UTC, nanuuki commented on tests/accounts_service_test.go
> +	if acccounts, err := svcs[0].List(0, 0); err != nil {
typo; `acccounts` => `accounts`

2021-12-17 09:26 UTC, nanuuki commented on tests/internal/test/service.go
> +		jobStore, 100, 1,
This could utilize `cfg.WorkerCount`  and maybe also `cfg.WorkerQueueCapacity` - thoughts?

2021-12-17 09:26 UTC, nanuuki commented on tests/accounts_service_test.go
> +	cfg.WorkerCount = uint(accountsToCreate / instanceCount)
This doesn't seem to affect the services returned by `test.GetServices` atm.

2021-12-17 09:26 UTC, nanuuki commented on main_test.go
> +		jobStore, 100, 1,
Note; the pool capacity affects the `async create exceeding worker pool capacity` test case also.

2021-12-21 08:22 UTC, nanuuki commented on jobs/jobs.go
> +	Attributes             datatypes.JSON `grom:"attributes"`
```suggestion
	Attributes             datatypes.JSON `gorm:"attributes"`
```

2021-12-21 08:27 UTC, latenssi commented on jobs/jobs.go
> +	Attributes             datatypes.JSON `grom:"attributes"`
Nice 👍

2021-12-21 08:30 UTC, nanuuki commented on migrations/internal/m20211220/migration.go
> +// m20211220 handles IdempotencyStoreGormItem migration
🔧

2021-12-21 08:57 UTC, nanuuki commented on tests/internal/test/service.go
> +	// keyCount, err := km.InitAdminProposalKeys(ctx)
I'd remove the commented code, or add a `TODO` if it's waiting for updates to the `InitAdminProposalKeys` implementation

2021-12-21 09:43 UTC, nanuuki approved these changes
Nice work! 👍

2021-12-21 09:50 UTC, merged